### ISSUE TITLE
Is UniqueIdentifier supported as a primary key on SQL Azure?

### ISSUE THREAD

**Issue by betaphreak** [nHydrate/nHydrate#1]
The SQL exception is "Operand type clash: uniqueidentifier is incompatible with tinyint" originating in 5_Programmability. The stored procedure that was generated by nHydrate:

CREATE PROCEDURE [dbo].[gen_Language_Insert]
(
    @Culture [VarChar](20) = null,
    @Enabled [Bit],
    @Id [UniqueIdentifier] = null,
    @Name [VarChar](50),
    @CreatedDate [DateTime] = null,
    @CreatedBy [Varchar](50) = null,
    @ModifiedBy [Varchar](50) = null

)
AS
SET NOCOUNT OFF;

if (@CreatedDate IS NULL)
SET @CreatedDate = getutcdate()
DECLARE @ModifiedDate [DateTime]
SET @ModifiedDate = getutcdate()
IF (@Id < 0) SET @Id = NULL;
if ((@Id IS NULL))
BEGIN
INSERT INTO [dbo].[Language]([Culture],
    [Enabled],
    [Name],
    [CreatedDate],
    [CreatedBy],
    [ModifiedDate],
    [ModifiedBy])
VALUES
(
    @Culture,
    @Enabled,
    @Name,
    @CreatedDate,
    @CreatedBy,
    @ModifiedDate,
    @ModifiedBy
);

if (@@RowCount = 0) return;

END
ELSE
BEGIN
SET identity_insert [dbo].[Language] on
INSERT INTO [dbo].[Language]([Id],
    [Culture],
    [Enabled],
    [Name],
    [CreatedDate],
    [CreatedBy],
    [ModifiedDate],
    [ModifiedBy])
VALUES
(
    @Id,
    @Culture,
    @Enabled,
    @Name,
    @CreatedDate,
    @CreatedBy,
    @ModifiedDate,
    @ModifiedBy
);

if (@@RowCount = 0) return;

SET identity_insert [dbo].[Language] off
END

SELECT 
    [dbo].[Language].[Culture],
    [dbo].[Language].[Enabled],
    [dbo].[Language].[Id],
    [dbo].[Language].[Name],
    [dbo].[Language].[CreatedBy],
    [dbo].[Language].[CreatedDate],
    [dbo].[Language].[ModifiedBy],
    [dbo].[Language].[ModifiedDate],
    [dbo].[Language].[Timestamp]

FROM
[dbo].[Language]
WHERE
    [dbo].[Language].[Id] = SCOPE_IDENTITY();

**Comment by gravbox** [comment]
I know that this is way late but I have verified that this no longer happens. It has been fixed sometime in between. The new 6.0 version uses EF6 and has many more features.

**Comment by gravbox** [comment]
Normally we do not use CRUD stored procedures. These are more for people who have DBA's who are real pains. I suggest turning these off, especially if you use EF6.

**Comment by gravbox** [comment]
Closed
