### ISSUE TITLE
Compilatio error for inheriting entities

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#10]
Hi,

Using the latest vsix package from VisualStudioGallery, I got a compile error. It shows up only for entities inheriting from another entity. For example, I have a an entity Employee which inherits from the entity Person. In there, in the IEmployee.Generated.cs, there is a definition for the enumeration

public new enum EmployeeFieldNameConstants 

The "new" keyword is what causes the problem. The error is:
Keyword 'new' is not allowed on elements defined in a namespace 

It looks like the "new" keyword is somewhere in the template causing the problem

Best regards,
Alex Prinias

**Comment by gravbox** [comment]
We are looking at this today. I will get back with you a little later.

Thanks,
Chris

**Comment by alprinias** [comment]
Thank you, Chris.
Don't know if this helps, after removing the new manually,  I got lots of compile errors (one for every entity in my model) in my main generated entities file (PsycheEntities.Generated.cs) indicating 
 'Dinaris.Psyche.EFDAL.Interfaces.IPsycheEntities.Profession' in explicit interface declaration is not a member of interface D:\Dinaris\Software\Solutions\Psyche\Dinaris.Psyche.EFDAL\PsycheEntities.Generated.cs 
and in the not-generated entities file (PsycheEntities.cs)
 'Dinaris.Psyche.EFDAL.PsycheEntities' does not implement interface member 'Dinaris.Psyche.EFDAL.Interfaces.IPsycheEntities.Profession'. 'Dinaris.Psyche.EFDAL.PsycheEntities.Profession' cannot implement 'Dinaris.Psyche.EFDAL.Interfaces.IPsycheEntities.Profession' because it does not have the matching return type of 'System.Linq.IQueryable<Dinaris.Psyche.EFDAL.Interfaces.Entity.IProfession>'. D:\Dinaris\Software\Solutions\Psyche\Dinaris.Psyche.EFDAL\PsycheEntities.cs 
Thanks again,Alex

```
  Απο: Christopher Davis <notifications@github.com>
```

 Προς: nHydrate/nHydrate nHydrate@noreply.github.com 
Κοιν.: alprinias alprinias@yahoo.gr 
 Στάλθηκε: 2:32 μ.μ. Παρασκευή, 8 Μαΐου 2015
 Θέμα: Re: [nHydrate] Compilatio error for inheriting entities (#10)

We are looking at this today. I will get back with you a little later.

Thanks,
Chris

**Comment by gravbox** [comment]
Would you send your model files to chrisd@gravitybox.com please? I would like to verify all of this. Also are you using EF 6 Code first templates?

**Comment by alprinias** [comment]
I've sent it. I am using the EF Data Access Layer (NOT the code-first). This was an upgrade from version 5.3.0.133.

**Comment by mtgibbs** [comment]
This should be fixed under commit fcb51f161235661569c9af37acc1e4d8dedc83a6

**Comment by alprinias** [comment]
Hello again,

Is there a new vsix package in Visual studio gallery or should we use the source code from GitHub?

**Comment by mtgibbs** [comment]
We're building a new release shortly.  Just hang tight.

**Comment by alprinias** [comment]
Thank you guys!
Alex

**Comment by gravbox** [comment]
There is a new release 143 that addresses this issue.
