### ISSUE TITLE
Adding new entity, error: "The field 'ID' must be between 1 and 32767"

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#11]
Hi,

After upgrading from to the latest version (5.3.0.143 VS gallery) from 5.3.0.133 and using now EF6 code-first templates I could not generate new entities with integer identity primary key. At SaveChanges, an Entity Validation exception is raised with the error message being "The field 'ID' must be between 1 and 32767". (ID is the primary key column, with type smallint)
Creating a new toy model with a single entity it all works fine. Comparing my model with the newly created one, I found the difference being a min value set for the ID field to 1. When I set this minimum also in the new model, i got the same exception.

This used to work in the non-code first approach and of course it is a minor issue, but just in case somebody else has the same problem this finding could save him/her some time.

All the best,
Alex

**Comment by gravbox** [comment]
This will be fixed in the next version by not allowing an Identity to have a range check. EF requires the PK int ID to not be null so it is 0. There will be a validation rule at generate time that will not allow this situation.
