### ISSUE TITLE
Read Only field

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#12]
Hi everybody and Happy New Year!

I was wondering what is the purpose of the "Is ReadOnly" flag for an entity field. I can see that it is used to generate some error messages in the SetValue method of each entity, which however is not used, or at least I don't use it as I prefer Entity.Property = xxx instead of Entity.SetValue(Property, Value). I would expect that it also annotates the entity properties by a [ReadOnly(true)] but it does not. Am I missing something?

All the best,
Alex

**Comment by gravbox** [comment]
This was not carried over from the EF4 templates. In the next release, a read-only column will be marked read-only. It will be read out of the database but will not be saved in the persist script. Look for this soon.
