### ISSUE TITLE
Making column NOT NULL when indexed

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#13]
Hi,

I tried to change a column from NULL to NOT NULL and I run into a problem because SQL Server indicates that the column participates in an index. Is there a recommended solution apart from the (obvious) drop the index and recreate it after changing the column? By the way, the column does not contain any NULL's at the moment.

Thanks a lot,
Alex

**Comment by gravbox** [comment]
We always drop the index and let the script run. The create script will re-add the index later if it is missing. I do not think you can modify a column data type or null setting when an index exists.
