### ISSUE TITLE
For EF6 generation ApendUsingStatements() should use new namespaces

### ISSUE THREAD

**Issue by betaphreak** [nHydrate/nHydrate#2]
Found http://msdn.microsoft.com/en-us/data/upgradeef6.aspx
nHydrate.Generator.EFDAL.Interfaces for EF6 should be using System.Data.Entity.Core instead of the old System.Data.Objects.DataClasses and Objects

There are also 45 references in nHydrate.Generator.EFCodeFirst that need to be changed.

**Comment by gravbox** [comment]
EF6 no longer has interfaces. The whole project is gone.

**Comment by gravbox** [comment]
EF6 no longer has interfaces. The whole project is gone.
