### ISSUE TITLE
Columns all marked as "Computed" in Generated SSDL file

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#23]
Recently Updated Model from 4.1.X to 6.0.0.177

Worked through code changes, could not save a changed entity and got the following exception;

> Modifications to tables where a primary key column has property 'StoreGeneratedPattern' set to 'Computed' are not supported. Use 'Identity' pattern instead. Key column: 'ID'.

Here is a snippet from the table in question from the SSDL;

```

        <Key>
            <PropertyRef Name="ID" />
        </Key>
        <Property Name="AccountDescription" Type="nvarchar" Nullable="true" MaxLength="64" StoreGeneratedPattern="Computed" />
        <Property Name="DomainAccount" Type="nvarchar" Nullable="true" MaxLength="64" StoreGeneratedPattern="Computed" />
        <Property Name="FailureCount" Type="int" Nullable="false" StoreGeneratedPattern="Computed" />
        <Property Name="ID" Type="int" Nullable="false" StoreGeneratedPattern="Computed" />
        <Property Name="IsActive" Type="bit" Nullable="false" StoreGeneratedPattern="Computed" />
        <Property Name="IsLockedOut" Type="bit" Nullable="false" StoreGeneratedPattern="Computed" />
        <Property Name="LastFail" Type="datetime" Nullable="true" StoreGeneratedPattern="Computed" />
        <Property Name="LastLockout" Type="datetime" Nullable="true" StoreGeneratedPattern="Computed" />
        <Property Name="LastLogin" Type="datetime" Nullable="true" StoreGeneratedPattern="Computed" />
        <Property Name="Password" Type="nvarchar" Nullable="false" MaxLength="256" StoreGeneratedPattern="Computed" />
        <Property Name="Salt" Type="nvarchar" Nullable="false" MaxLength="64" StoreGeneratedPattern="Computed" />
        <Property Name="Username" Type="nvarchar" Nullable="false" MaxLength="50" StoreGeneratedPattern="Computed" />
        <Property Name="ModifiedBy" Type="varchar" MaxLength="50" />
        <Property Name="ModifiedDate" Type="datetime" />
        <Property Name="CreatedBy" Type="varchar" MaxLength="50" />
        <Property Name="CreatedDate" Type="datetime" />
        <Property Name="TimeStamp" Type="timestamp" Nullable="false" StoreGeneratedPattern="Computed" />
```

After trying to track down why this is happening I found the following Function in Hydrate/Source/nHydrate.Generator.EFDAL/HelperExtension.cs;

```
        public static string ToEFStoreGeneratedPattern(this ColumnBase column)
        {
            string retVal = null;
            if (column is Column)
            {
                if (((Column)column).Identity == IdentityTypeConstants.Database)
                    retVal = "Identity";
                if (((Column)column).ComputedColumn)
                    retVal = "Computed";
            }
            else if (column is CustomViewColumn)
            {
                retVal = string.Empty;
            }

            retVal = "Computed";
            return retVal;
        }
```

This code appears to not care what the column type is and set it to Computed.

Steve

**Comment by midnight-sun** [comment]
I forked so I could test the change; It works in my case, but I am not 100% familiar with the underpinnings of EF to create a pull request.

[changeset in my working copy](https://github.com/midnight-sun/nHydrate/commit/0b8880c38826e1d53a1329007d92b1f3172892c4)

Let me know,

Steve

**Comment by midnight-sun** [comment]
Is there any word on this issue?  I can't update my plug-in until I can generate without the columns being marked 'Computed'.  (I am currently using my modified version of nHydrate.Generator.EFDAL.dll)

Steve

**Comment by mtgibbs** [comment]
I'm sorry that this issue fell on deaf ears @midnight-sun.  I was going through the issues today and realized that you never got a response.  Given that this is such an old issue, do you still have these concerns with the newer versions of the plugin?

**Comment by midnight-sun** [comment]
Matt,
I think this is good and can be closed.  I am confident that I have been updating my plugin fairly regularly in the last few months and had no problems with my last generation.

Can yo close this, if I encounter an issue with my next generation (looking at next month) I will reopen the ticket.

Thanks,

Steve

**Comment by mtgibbs** [comment]
👍
