### ISSUE TITLE
Feature Request - Diagram only Certain Entities

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#25]
I love working with the diagram, but with 100 Entities or so in my model right now it becomes difficult to navigate and use effectively.

I would like to propose the ability to filter the diagram to only a certain subset of the model.  Initially, I thought that this might be accomplished through putting them into a module; and then maybe working with a diagram of that module alone and removing the module functionality prior to generation.  

Maybe the model could allow multiple diagrams which you could add [entities / view / sp / fn]'s to for organizational and modification purposes only and would not affect generation.

Thanks,

Steve

**Comment by gravbox** [comment]
I know this is a pain point. However in the version of the DSL used I see no way to do this. There is a way to find an entity. The nHydrate Object View window (dockable) will let you filter and click on an entity to bring it up in the model. We use this because we have hundreds of tables. See if this will suit your needs.

**Comment by midnight-sun** [comment]
Me being the Genius I am closed that window when I first opened the model.  I have been poking around ever since in an attempt to reopen it.

**Comment by gravbox** [comment]
Click Vlew|Other Windows|nHydrate Explorer
I think that this will show all the windows.

**Comment by midnight-sun** [comment]
I can't tell you how many times I must have moused right over that.

I'm going to close this 'issue', the object view will at least make it easier to access relationships.

Hopefully, a visual/diagram solution presents itself in future iterations.

**Comment by gravbox** [comment]
Also if you want to add relations on a large diagram, just right on an entity and click Model|Relationships. This will allow you to add a relation without dragging. On a large diagram this is really the only way to add a relation since entities could be far apart.
