### ISSUE TITLE
Error in Install project

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#26]
Hi,

I had upgraded to the latest version about 10 days ago but didn't do any database update since then. Now I just made a small change (added an extra field to a view), generated and tried to update the database by runing the Install project. Then after the command prompt had opened and before any form appears I got an error coming from the UpgradeInstaller.cs file. The error details are listed below. 
Any idea?
Best regards,
Alex

System.Security.Cryptography.CryptographicException occurred
  HResult=-2146233296
  Message=Padding is invalid and cannot be removed.
  Source=System.Core
  StackTrace:
       at System.Security.Cryptography.CapiSymmetricAlgorithm.DepadBlock(Byte[] block, Int32 offset, Int32 count)
       at System.Security.Cryptography.CapiSymmetricAlgorithm.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
       at Dinaris.Psyche.Install.Extensions.Decrypt(String text) in d:\Dinaris\Software\Solutions\Psyche\Dinaris.Psyche.Install\UpgradeInstaller.cs:line 2228
  InnerException:

**Comment by gravbox** [comment]
Just delete the "installsettings.xml" file. It has an invalid encrypted string. The error handler is supposed to  return null and it should run. Doesn't the error hit the handler and return null?

**Comment by alprinias** [comment]
Hi,
Thanks for your reply. The error occurs in the following piece of code, at the first of the two lines in the using() block. There is a catch which indeed returns null, but VS stops at the line I have marked. If i hit continue, it goes to the catch, returns null, goes on, but fails again at the same line immediately afterwards.
In any case, after deleting the Install\bin\installsettings.xml file, it worked. Thank you very much.
Alex

```
        try
        {
            var aes = new AesCryptoServiceProvider();
            aes.BlockSize = 128;
            aes.KeySize = 128;
            aes.IV = Encoding.UTF8.GetBytes(IVKey);
            aes.Key = Encoding.UTF8.GetBytes(CryptKey);
            aes.Mode = CipherMode.CBC;
            aes.Padding = PaddingMode.PKCS7;

            // Convert Base64 strings to byte array
            byte[] src = System.Convert.FromBase64String(text);

            // decryption
            using (ICryptoTransform decrypt = aes.CreateDecryptor())
            {
```

======>         byte[] dest = decrypt.TransformFinalBlock(src, 0, src.Length);
                    return Encoding.Unicode.GetString(dest);
                }

```
        }
        catch (Exception ex)
        {
            return null;
        }
```
