### ISSUE TITLE
View links

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#29]
Hi,
How do View Links work? I linked an entity, let's say Person with properties LasName/FirstName, to the view PersonView with a (calculated) property FullName and I was expecting to be able to access FullName from Person with something like 

var person = context.Person.FirstOrDefault(n => n.ID == xx);
var fullName = person.PersonView.FullName;

However, no such thing exists. Am I missing something?

Best regards,
Alex

**Comment by gravbox** [comment]
This is left over from EF4 and I do not think that it is supported in EF6.
