### ISSUE TITLE
Associative tables should not be allowed when both tables have the same primary key name

### ISSUE THREAD

**Issue by betaphreak** [nHydrate/nHydrate#3]
At first you won't find any obvious error, but this is what you get with ASP.NET Dynamic Data when you feed it the generated code:

Id: Name: Each property name in a type must be unique. Property name 'Id' is already defined.
Id: Name: Each property name in a type must be unique. Property name 'Id' is already defined.
X: EntityType: EntitySet 'X' is based on type 'X' that has no keys defined.

The troublesome code being generated is q.MapLeftKey("Id") and q.MapRightKey("Id") in my case.

**Comment by gravbox** [comment]
How do you reproduce this? First you cannot name two fields in the associative table the same name. The validation rule will catch it. If the names in the two parent tables are the same it works. Please explain more or attach a model file.

**Comment by betaphreak** [comment]
Initially I left all the default names for the primary keys of my tables as "ID". So make an associative table on T1 and T2 with T1.ID -> id1 and T2.ID -> id2. This works but will cause problems further on if I try to use it like this. So it would make sense to disallow it explicitly

**Comment by gravbox** [comment]
The modeler has been updated to support Entity Framework Core. Please use this version is possible.
