### ISSUE TITLE
An unknown error

### ISSUE THREAD

**Issue by ronea23** [nHydrate/nHydrate#30]
Team, As suggested according to the manual have configured / installed the extension in VS 2010 Professional version.

But attached error is shown, am failing to understand whats gone wrong.

Any help would be appreciated...

![nhyderate_er](https://cloud.githubusercontent.com/assets/10896354/18240027/c8788f54-7366-11e6-9f14-3644a1d23c60.png)

Thanks,
Ronald

**Comment by gravbox** [comment]
I am sorry about this however we do not test in VS2010. Currently we have only 2013 and V2015 setup. Please try to upgrade to one of these versions.

**Comment by ronea23** [comment]
Thanks for the clarification.

Regards,

Ronald

**Comment by mtgibbs** [comment]
Referencing commit e6b15db9ed74b99b8a888580f9a3db49b9820122

The modeler should not be marked as supported in VS 2010 now on the marketplace.
