### ISSUE TITLE
Not Null fields and Required Annotation

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#31]
Hi,
Please correct me if I'm mistaken, but weren't "Not Nullable" entity properties annotated with the "Required" data attribute? I used to use it for validation and just noticed it is now missing. Is that done on purpose and there is now a preferred way of indicating Not Nullable properties?

Best,
Alex

**Comment by gravbox** [comment]
This was removed because the fluent syntax describes the object to EF. However I see how this is useful for reflecting on the object. This attribute will be added back to the object definition in the next version.

**Comment by alprinias** [comment]
Can one check if IsRequired is set for an entity property with the fluent syntax?
