### ISSUE TITLE
Dropped Table Column still present in Database

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#32]
Hi,

What happens if we drop a table column from our model? I Just noticed that a column I had dropped in my model at some point is still present in the database table. The table is empty, so there shouldn't be any data constraints that interfered with dropping the column. Is there any way to check that a database is in sync with a model?

Best,
Alex

**Comment by mtgibbs** [comment]
The behavior for dropped columns is that the column remains in the database and must be manually removed.

For your second question: Can you clarify what you mean by checking if your model and database are synchronized?  nHydrate writes its own tables ```__nhydrateobjects``` and ```__nhydrateschema``` that can be queried for finding out what version of upgrade you are on and more.

**Comment by gravbox** [comment]
A removed column actually should be removed. Look at the last upgrade script. There should be a drop column script generated. If there is not then there is an issue.

Also there is a way to verify database and C# code matches. On the context look at the methods "IsValidConnection" and "GetDBVersion". These compare the database version with the code version.

**Comment by alprinias** [comment]
Actually, I had not removed the column, I had renamed it. And that resulted in the table containing two columns, one with the old name and one with the new one.

Concerning the comparison... In my case the versions were the same in code and database, but the model had one column in the table and the database had two. So I am talking about a comparison like e.g. printing out all table columns from db and all table columns from the model and comparing the two lists.

**Comment by gravbox** [comment]
I am sorry but I do not see this behavior. There is a generated rename script. I have a field "Name" and I renamed it to "Name2". This is the generated script. Do you not see a rename script?

--RENAME COLUMN 'Company.Name'
if exists (select * from syscolumns c inner join sysobjects o on c.id = o.id where c.name = 'Name' and o.name = 'Company') AND not exists (select * from syscolumns c inner join sysobjects o on c.id = o.id where c.name = 'Name2' and o.name = 'Company')
EXEC sp_rename @objname = 'Company.Name', @newname = 'Name2', @objtype = 'COLUMN';

**Comment by alprinias** [comment]
Hi,
You are right, I see this kind of rename scripts in my upgrade scripts. 

But to be honest, I can't remember now which exact table/column I was referring to in my original post, so that I search specifically for the rename script for that column. What I mean is, could it be that when I tried it in the past for that specific column, you hadn't yet implemented the rename functionality? 

Alex

**Comment by gravbox** [comment]
The generated scripts should handle this situation. However you have full control over the scripts. If there is some action that you need to perform put it in the generated script file. They are a base, but there may be custom actions that need to be added.
