### ISSUE TITLE
Exception when deleting entity

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#33]
Hi, 

I was trying to delete a record from my database and ran into an exception stating 
"The connection string was not found.". This comes from the GetConnectionString() method, which is called in the following block processing the deleted items, located in the SaveChanges() method. 

1. The GetConnectionString() method cannot find a connection string because it tries to find it in the configuration which I am not using, instead I construct the string in code.

2. In any case, the connection built in the following block does not seem to be used, it is just opened and 
finally closed, the SqlCommand following the opening of the connection does not use the connection.

3. Finally, what is the purpose of the block? The check ```if (...  && entity.ModifiedBy != this.ContextStartup.Modifer)``` puzzles me. I had not ran into the problem before since my ContextStartup.Modifier was the same as the ModifiedBy, so I was not entering the if block. 

Best,
Alex

```csharp
//Process deleted list
var deletedList = this.ObjectContext.ObjectStateManager.GetObjectStateEntries(System.Data.Entity.EntityState.Deleted);
foreach (var item in deletedList)
{
	var entity = item.Entity as IAuditable;
	if (entity != null)
	{
		if (entity.IsModifyAuditImplemented && entity.ModifiedBy != this.ContextStartup.Modifer)
		{
			System.Data.SqlClient.SqlConnection connection = null;
			try
			{
				connection = new System.Data.SqlClient.SqlConnection(GetConnectionString());
				connection.Open();
				System.Data.SqlClient.SqlCommand command = null;
				if (command != null)
				{
					command.CommandType = System.Data.CommandType.Text;
					if (this.ContextStartup.Modifer == null)
						command.Parameters.Add(new System.Data.SqlClient.SqlParameter("@mod", System.DBNull.Value));
					else
						command.Parameters.Add(new System.Data.SqlClient.SqlParameter("@mod", this.ContextStartup.Modifer));
					command.ExecuteNonQuery();
				}
			}
			catch
			{
				throw;
			}
			finally
			{
				if (connection != null && connection.State == System.Data.ConnectionState.Open)
					connection.Close();
			}
		}
	}
}
```

**Comment by gravbox** [comment]
this is old code that is not used anymore as it was for some other purpose. it will be removed in the next version. thanks.
