### ISSUE TITLE
Remove use of ApplicationException

### ISSUE THREAD

**Issue by jeremyhayes** [nHydrate/nHydrate#34]
Per MSDN remarks, System.ApplicationException was an early mistake, and should not be used by application code.
https://msdn.microsoft.com/en-us/library/system.applicationexception.aspx

Additionally, this exception type is not available in .NET Core/Standard.

There are two uses in generated code (at least in our usage, with EF6 code-first templates):
 - In the Install project, `SqlServers.GetServers:99`
https://github.com/nHydrate/nHydrate/blob/master/Source/nHydrate.Generator.EFCodeFirst/Generators/Helpers/HelperGeneratedTemplate.cs#L1253
 - In the EFDAL project, the `nHydrateException` derives from `ApplicationException`
https://github.com/nHydrate/nHydrate/blob/master/Source/nHydrate.Generator.SQLInstaller/ProjectItemGenerators/DatabaseEmbeddedClasses/SqlServers.cs#L99

**Comment by gravbox** [comment]
This is done.
