### ISSUE TITLE
How to remove Identity from column

### ISSUE THREAD

**Issue by alprinias** [nHydrate/nHydrate#35]
Hi,
What is the recommended procedure for removing the Identity from a column? I changed the Identity property from 'Database' to 'None' but this didn't work.
Best,
Alex

**Comment by mtgibbs** [comment]
It didn't remove it in the modeler or when you ran the upgrade?

**Comment by alprinias** [comment]
It didn't remove it when I ran the update. 
It is quite a tricky business anyway. When you do it in SSMS, the underlying script creates a new table without the identity and copies the data to it and renames it to the original table name.
Additionally, my table had already data in it. I don;t know what would have happened if it was an empty table.

Best,
Alex

**Comment by gravbox** [comment]
You cannot remove an IDENTITY specification once set. This is just a quirk of SQL Server. However you can do it in a round about way. You will have to drop any relationships that the column participates in and follow these directions. Sorry it is so complicated.

- Create a new column
- Transfer the data from the existing IDENTITY column to the new column
- Drop the existing IDENTITY column.
- Rename the new column to the original column name

**Comment by gravbox** [comment]
After looking into this, the next version will have scripts emitted to handle this situation. It will follow the steps above to create a temp column and move the data. The script will handle the basic situations but can be modified to handle more complex, custom scenarios that you might have.

**Comment by alprinias** [comment]
Yes, it's quite complicated, I know...
Thanks, Chris.
Alex

**Comment by mtgibbs** [comment]
Referencing the commits with this discussion.

https://github.com/nHydrate/nHydrate/commit/0a4bc700fb0689450e3374cd11e7aa740f00e748
https://github.com/nHydrate/nHydrate/commit/ae0492b3e95bde90392e6724b8419c7f4b2f50d4

**Comment by gravbox** [comment]
This will be in the next version as soon as we get it to work in VS 2017. The templates have been changed.
