### ISSUE TITLE
VS 2013 - Compatability

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#36]
Attempted to update to *.201, but it the gallery says that the extension doesnt support the product.  I assume that there were changes to project files to be compatible with VS 2017.

Here is me hoping that something can be done to be compatible with both versions.  We are not quite ready to pull the trigger on VS 2017 yet.

Thanks!

Steve

**Comment by gravbox** [comment]
Please try again as I have updated it. If you cannot install it from the extension box, please download it from the gallery here.
https://marketplace.visualstudio.com/items?itemName=nHydrateorg.nHydrateORMModeler

It should install in 2013.

**Comment by midnight-sun** [comment]
Same thing, this is the screenshot (downloaded from the marketplace, as I ran into the same thing from the extension manager)

![image](https://cloud.githubusercontent.com/assets/8062166/24167078/1b127648-0e3b-11e7-9953-91ff66d187fe.png)

And the install log:
3/21/2017 1:32:37 PM - Microsoft VSIX Installer
3/21/2017 1:32:37 PM - -------------------------------------------
3/21/2017 1:32:37 PM - Initializing Install...
3/21/2017 1:32:37 PM - Extension Details...
3/21/2017 1:32:37 PM - 	Identifier      : 36220dab-63c7-4daa-860c-fc548bf4d5d3
3/21/2017 1:32:37 PM - 	Name            : nHydrate ORM Modeler
3/21/2017 1:32:37 PM - 	Author          : nHydrate.org
3/21/2017 1:32:37 PM - 	Version         : 6.0.0.201
3/21/2017 1:32:37 PM - 	Description     : This is the nHydrate Visual Modeler
3/21/2017 1:32:37 PM - 	Locale          : en-US
3/21/2017 1:32:37 PM - 	MoreInfoURL     : 
3/21/2017 1:32:37 PM - 	InstalledByMSI  : False
3/21/2017 1:32:37 PM - 	SupportedFrameworkVersionRange : [4.5,)
3/21/2017 1:32:37 PM - 
3/21/2017 1:32:37 PM - 	Supported Products : 
3/21/2017 1:32:37 PM - 		Microsoft.VisualStudio.Community
3/21/2017 1:32:37 PM - 			Version : [12.0,15.0]
3/21/2017 1:32:37 PM - 
3/21/2017 1:32:37 PM - 	References      : 
3/21/2017 1:32:37 PM - 
3/21/2017 1:32:37 PM - Searching for applicable products...
3/21/2017 1:32:39 PM - Found installed product - Microsoft Visual Studio Professional 2013
3/21/2017 1:32:39 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
3/21/2017 1:32:39 PM - Found installed product - Global Location
3/21/2017 1:32:39 PM - Found installed product - ssms
3/21/2017 1:32:39 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by mtgibbs** [comment]
Is there any concern with using VS 2015 then?  It's more than stable enough at this point.

@gravbox Perhaps explicitly marking Professional as an option would solve this?

```
<InstallationTarget Version="[12.0,15.0]" Id="Microsoft.VisualStudio.Professional" />
```

**Comment by midnight-sun** [comment]
At this point in my cycle, moving to a new development environment introduces to much risk.  I should be able to update in the coming months.  Then the team will likely just move all the way up to 2017.

nhydrate is compatible with 2017 right?

**Comment by mtgibbs** [comment]
Yep.  As far as our testing shows at least.  We're all using it in VS 2017.

**Comment by midnight-sun** [comment]
Should I hold any hope that 2013 will be compatible before that upgrade occurs?

Either way thanks for all the hard work and the project I now cannot live without.

Steve

**Comment by mtgibbs** [comment]
Chris is the only one who even has 2013 still installed most likely.  Which is weird because it obviously worked for him when he was trying to help you.  So if we find out what's different we'll definitely publish the change.

**Comment by midnight-sun** [comment]
Has there been any progress on this issue or am I SOL in my groups current visual studio environment?

Thanks,

Steve

**Comment by mtgibbs** [comment]
@midnight-sun Sorry.

@gravbox was never able to reproduce this problem when he installed it in VS 2013 and no one else on the project or projects using nhydrate use the older versions of VS anymore.  😦 Best and easiest bet is to bite the bullet and upgrade to a newer version of Visual Studio.

**Comment by midnight-sun** [comment]
@gravbox, can you just verify for me the version of 2013 that you were successful installing this on?  I am just looking for a quick fix until I can get my team transitioned (probably a couple of months).

I am on Vs 2013 Update 5 [12.0.40629.00]

Thanks,

Steve

**Comment by mtgibbs** [comment]
@midnight-sun 

Alright.  So in our testing we figured out why it worked for our 2013 installs.  For some reason the new format for 2017 requires some of the VS 2017 dlls.  Since our machines all have 2015 and 2017 on them, the dlls seem to be available and it works regardless of what version we're using.  So we've narrowed it down a bit, though not much hope in how to fix it....  

A workaround for you for the time being though could be to simply install VS 2017 on your work machines and not migrate your project.

**Comment by midnight-sun** [comment]
@mtgibbs This is good news,  I will install vs 2017 and 2013 side-by-side and see if an update of nHydrate is possible.  I appreciate you looking deeper into this!

I will test it on my machine in the coming week so as not to affect the team.  In the meantime I am going to go ahead and close this one, as it is just a case of me getting with the times.

You might want to drop VS 2013 from the compatibility list in the Visual Studio Marketplace.

![image](https://user-images.githubusercontent.com/8062166/28276218-73e3c548-6ad3-11e7-9ef2-61472a24dfa0.png)
