### ISSUE TITLE
GetAuditRecords Fails

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#37]
Preface; my currently generated EFDAL is from generator version 6.0.0.192.  I did look into the source and the bug seems to still exist.

The connection cannot open when making the call  ENTITY.GetAuditRecords().  The code goes eventually to the function;
` ENTITYAudit.Generated.cs > GetAuditRecords(pageOffset, recordsPerPage, startDate, endDate, id, connectionString) : dbConnection.Open();`

This fails because the connectionString passed does not contain the complete credential information and the logon fails.  This issue is rectified if I turn PersistSecurityInfo=True in the connectionstring in the web.config, this is not ideal.  Previously, this function seemed to grab its connection string directly from <Application>Entities.getConnectionString().

Does this make any sense?

Steve

**Comment by gravbox** [comment]
I assume you mean because the method "GetAuditRecords" is using this for the connection string
"Test44Entities.GetConnectionString()" instead of a connection string you passed into the context. Is this right? If you put the connection string in the web/app.config file it works right?

**Comment by midnight-sun** [comment]
No, I mean that I have the connection string in the config file.  There is a line in "GetAuditRecords" which gets this and turns it into a string.  Without "PersistSecurityInfo" this string GetAuditRecords passes to the next function does not contain the password required to connect to the datastore.

`this._internalContext.ConnectionString` does not contain the password information.

**Comment by gravbox** [comment]
That will be fixed in the next version.
