### ISSUE TITLE
Composite key - crashes SaveChanges() in EFDAL

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#38]
We have a table with a composite key that causes us issues in _APPNAME_Entities.Generated.cs of our EFDAL  for instance:

```cs
else if (entity is XX.YY.EFDAL.Entity.caAppDeclineReasons)
{
   command = new System.Data.SqlClient.SqlCommand("UPDATE [dbo].[caAppDeclineReasons] SET [ModifiedBy] = @mod WHERE [ApplicationID] = @pk1 AND [DeclineReasonID] = @pk2 AND (([ModifiedBy] != @mod) OR ([ModifiedBy] IS NULL AND @mod IS NOT NULL) OR ([ModifiedBy] IS NOT NULL AND @mod IS NULL))", connection);
   command.Parameters.Add(new System.Data.SqlClient.SqlParameter("@pk1", ((XX.YY.EFDAL.Entity.caAppDeclineReasons)entity).ApplicationID));
   command.Parameters.Add(new System.Data.SqlClient.SqlParameter("@pk1", ((XX.YY.EFDAL.Entity.caAppDeclineReasons)entity).DeclineReasonID));
}
```

You will notice that the second parameter has a name of `@pk1` when it should be `@pk2`.  This bug is in `ContextGeneratedTemplate`, the loop surrounding the `line 1052` never increments the counter `ii` as it does in the previous loop.

As an aside, I am still working in Visual Studio 2013 so cannot update to the most recent version of nHydrate even when you do fix the bug.  Here's hoping that issue clears up too.

If you need additional information to fix this issue please let me know,

Steve

**Comment by gravbox** [comment]
We know about this. It has been fixed. I need to check if the fixed version has been published or not.

**Comment by midnight-sun** [comment]
@gravbox  I just checked the current source and this appears to still be an issue in the main branch on github.

**Comment by gravbox** [comment]
I have just checked this into the source but it is not built.
