### ISSUE TITLE
on using ef 6 templates and database generation.

### ISSUE THREAD

**Issue by giannik** [nHydrate/nHydrate#4]
When using the ef6 templates to generate the project what is the recommended approach for the database creation and maintenance ?
Do we  generate the database install project templates or do we rely on EF's built in database migrations to handle database generations ?
Thanks

**Comment by gravbox** [comment]
Use the generated installer. There is a UI and API for creation or updating. The only thing to generate now is the (1) Code First and (2) Installer. These 2 projects are all you need to run the data layer.

**Comment by gravbox** [comment]
There is also a new modeler uploaded in the Visual Studio Gallery.
https://visualstudiogallery.msdn.microsoft.com/d641354e-b15f-437c-b7eb-83c6ac423651

**Comment by giannik** [comment]
thanks Chris.
Will do so.
