### ISSUE TITLE
.NET CORE support. 

### ISSUE THREAD

**Issue by boteklub** [nHydrate/nHydrate#41]
Hello, please, is there support nHydrate for .NET CORE and EF CORE?

**Comment by mtgibbs** [comment]
Not currently, though it is something we're experimenting with and hope to have in the near future.

**Comment by boteklub** [comment]
Great, thanks for the info. We'd like to start using nHydrate, I like it, but we use .net core solution.

**Comment by alprinias** [comment]
Hello,
Any news on this?

**Comment by dimov-cz** [comment]
+1

**Comment by gravbox** [comment]
We are hold for this until MS can provide the table inheritance functionality. This has been a showstopper for us.

**Comment by scharada** [comment]
Inheritance exists in efcore 
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance
https://docs.microsoft.com/en-us/ef/core/modeling/relational/inheritance

would be interesting to use it in net core and EF core...

any timeline on this since i see you started on it ?

**Comment by gravbox** [comment]
The newest posted version in the gallery (7.0+) is for .NET Core only. You can upgrade to it to model your Core data layers.
