### ISSUE TITLE
Specify Location to put nHydrate.EFcore on Generate

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#45]
In our project we have a "resources" directory where we store external code libraries.  nHydrate attempts to put it in the solutions bin folder (which I do not use), I would like to request the ability to change that location through a model setting.

On my most recent update I grabbed the dll from the extension directory manually and copied it there, and the last one was version 179 (hadn't been done in a while).  I also manually updated the references in "EFDAL.Interfaces" and "EFDAL", along with my couple other projects in the same solution that use it.

I'm not sure if there is anything that can be done above allowing me to auto update the dll they all reference stored in my "resource" folder.

For reference here is my solution layout including projects that use nHydrate;
- Main Solution
            Solution Items <where I copy the EFCore.dll, and model file location>
            Main Web Project (primary consumer of nHydrate)
            Security Code Library (membership/role provider, AD logon facilitator)
            EFDAL
            EFDAL.Interfaces
            NHDAL (really old, vestigial just to show you how log we've used the nHydrate)

I hope this makes sense, and I haven't just been using nHydrate wrong for 6 years.

Thanks to Chris and Team!

**Comment by gravbox** [comment]
Are you now using the EF 6 Code First version? If so there is no EFCore anymore.

**Comment by midnight-sun** [comment]
We are not using the code first version, please tell me it is not on the road map to discontinue support of not code first.  Here is an image of the generator screen with the projects we generate;
![image](https://user-images.githubusercontent.com/8062166/42644114-002caf74-85b8-11e8-88f4-46cb68b3c3d9.png)
