### ISSUE TITLE
Upgrade script won't work.  Computed columns can't be rename.

### ISSUE THREAD

**Issue by KarlRichard** [nHydrate/nHydrate#47]
Hi,

My upgrade script fails since a computed column can't be rename.

Generated script:

--RENAME COLUMN 'FiscalPeriod.FiscalMonth'
if exists (select * from sys.columns c inner join sys.tables t on c.object_id = t.object_id inner join sys.schemas s on t.schema_id = s.schema_id where c.name = 'FiscalMonth' and t.name = 'FiscalPeriod' and s.name = 'lookup')
		AND not exists (select * from sys.columns c inner join sys.tables t on c.object_id = t.object_id inner join sys.schemas s on t.schema_id = s.schema_id where c.name = 'Period' and t.name = 'FiscalPeriod' and s.name = 'lookup')
EXEC sp_rename @objname = '[lookup].[FiscalPeriod].[FiscalMonth]', @newname = 'Period', @objtype = 'COLUMN';

GO

The actual generated script should look something like this:

--RENAME COLUMN 'FiscalPeriod.FiscalMonth'
if exists (select * from sys.columns c inner join sys.tables t on c.object_id = t.object_id inner join sys.schemas s on t.schema_id = s.schema_id where c.name = 'FiscalMonth' and t.name = 'FiscalPeriod' and s.name = 'lookup')
		AND not exists (select * from sys.columns c inner join sys.tables t on c.object_id = t.object_id inner join sys.schemas s on t.schema_id = s.schema_id where c.name = 'Period' and t.name = 'FiscalPeriod' and s.name = 'lookup')
BEGIN
	DECLARE @Statement NVARCHAR(MAX) = 'ALTER TABLE [lookup].[FiscalPeriod] ADD [Period] AS ' + (select TOP(1) c.definition from sys.computed_columns c inner join sys.tables t on c.object_id = t.object_id inner join sys.schemas s on t.schema_id = s.schema_id where c.name = 'FiscalMonth' and t.name = 'FiscalPeriod' and s.name = 'lookup')
	ALTER TABLE [lookup].[FiscalPeriod] DROP COLUMN FiscalMonth
	EXEC sp_executesql @Statement
END

GO

**Comment by gravbox** [comment]
A generation note will be added to the script instead of failing. A manual rename will need to be manually created.
