### ISSUE TITLE
AuditCompare - Compare with empty or NULL

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#48]
For our audit log interface we list the date a commit was made and the fields that changed.  This works really well.  Unfortunately,  this does not seem possible for the insert or deleted actions.

A sample of what we do now (fails for insert as x is null);
//show code comparing to audits and getting the differences as a list of fields
`Audit.[ENTITY]Audit.CompareAudits((Audit.[ENTITY]Audit)x, (Audit.[ENTITY]Audit)y).Differences.ToList();`

What we would like to do;
//show code that sends in empty obj as item1 or item2
`Audit.[ENTITY]Audit.CompareAudits((Audit.[ENTITY]Audit)x ?? new Audit.[ENTITY]Audit() { [ENTITY]ID = 0 }, (Audit.[ENTITY]Audit)y).Differences.ToList();`
or keep the code the same and not have it crash because of a `NULL`.

Unfortunately `Audit.[EntityAudit]` is internal so we cannot create a blank one to send to `CompareAudits()` and `CompareAudits()` will not take null as either parameter.

The generator for this code in both EFDAL and CodeFirst appears to use the same technique;
[AuditEntityGeneratedTemplate](https://github.com/nHydrate/nHydrate/blob/master/Source/nHydrate.Generator.EFCodeFirst/Generators/AuditEntity/AuditEntityGeneratedTemplate.cs) > AppendCompare().  We currently have projects that work with each library.  

Ideally we'd like to pass `NULL` as `item1` or `item2` to `CompareAudits()`

Thanks in advance,

Steve

**Comment by gravbox** [comment]
Please post the code as you would like to use it and I will review. That method is only a few lines. Please modify it as you see fit and let me know.

**Comment by midnight-sun** [comment]
Will do except....

I do not have any examples of Binary columns to validate any changes so I will try and leave that section alone.  I don't imagine I will end up modifying much code.

Steve

**Comment by midnight-sun** [comment]
Created pull request #49 

Modify CompareAudits() to accept a null as parameter one or two

outputs all columns on when one of the parameters are `null`.

One thing I noticed is that EFDAL appears to handle BINARY columns in a special way and it looks like CODEFIRST doesn't handle them at all.  I chose not to rock the boat and just wrap the existing code and essentially duplicate it for a `null` in each case
