### ISSUE TITLE
Increasing Visibility of Audit for Deleted Items

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#50]
Currently trying to shore up an interface for an entity who has a sub entity list which can be deleted from.

It seems that it is quite difficult to retrieve audit records for an entity that you do not know the key for anymore (deleted)

It would be helpful if there was a way to get Auditable Entities  based on a foreign key, which I can then get the audit history for.

Right now I just grab the current entity list and grab the audit records for each of those entities, obviously this excludes any deleted entity.

Steve

**Comment by gravbox** [comment]
The latest version has a full context that you can query to pull back data with LINQ. Version 6.0.0.220. Look in the Audit folder. You can declare a context just like the normal context now.

**Comment by midnight-sun** [comment]
That was quick...
Unfortunately some of my project still uses EFDAL instead of CodeFirst so this additional functionality will only be available to the CodeFirst projects until I get the chance to update the older stuff.

Looking at the changes now.

Thanks Chris!
