### ISSUE TITLE
Download of earlier versions of nHydrate

### ISSUE THREAD

**Issue by HJ-626** [nHydrate/nHydrate#53]
Where can we download earlier versions of nHydrate from?

Updating a DB model with the latest version (6.5) in VS2017 has resulted in hundreds of errors appearing in the project. 

There doesn't seem to be any way for downloading the previous version (6.0) and github has no tracking of previous releases.

**Comment by gravbox** [comment]
First, would you post a few errors? This might be an issue. Please provide some details and I will get back to you.

**Comment by HJ-626** [comment]
The most common are:
- "CS0246  C# The type or namespace name 'DbSet<>' could not be found (are you missing a using directive or an assembly reference?)"
- "CS0234  C# The type or namespace name does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)"
These appear on the "using" lines when getting the database context and the lines below this when attempting to obtain a list from a DB lambda expression.

To obtain these errors, I updated the DB model as a result of a schema change (dropped and recreated table with new column, and new column in another table with an associated foreign key).

In the short term, if you're able to provide the previous version, that will hopefully allow us to proceed.  Thanks.

**Comment by gravbox** [comment]
Are you sure that you have added the entity framework 6.1.3 package to that project? This seems like it might be missing the proper references.

**Comment by HJ-626** [comment]
Yes, the Entity Framework version is already 6.2.0.

Just to clarify, we had previously been using nHydrate without issue up until today when we had to make a schema change and update the model.  As VS2017 was set to automatically update nHydrate, it has upgraded to 6.5.0 from 6.0.0.  This is the first time we have had to update the model with the new version, and as soon as we do this, lots of errors appear.

Prior to updating the model, there were no errors, with the last model update conducted with 6.0.0.

If we can just get 6.0.0 from somewhere and reinstall it, I think this will likely solve our issue.

**Comment by midnight-sun** [comment]
I did notice yesterday that the generators selected are now both core and
standard.  They overwrite each other.  You might want to verify that you
are generating just one, and the one you expect.

I'll try and post a screen shot when I get in in the morning

**Comment by HJ-626** [comment]
I've been able to search through my old downloads to find the previous version and have updated the model without issue (6.0.0.222).

It could be the two generators that is the issue - I did notice the 3 checkboxes instead of 2 in the previous version.

**Comment by gravbox** [comment]
That is a good point. The .NET standard is a beta right now. It is for .NET core projects. It does have the same generated namespace as the .NET Framework generator. You should not use it in your existing project. Use the generator called "EF Data Access Layer (v6)".

**Comment by gravbox** [comment]
The newest posted version (7+) in the gallery is for Entity Framework Core only. If you are using EF 4.x - 6.x the legacy version is available here http://nhydrate.org/downloads/nHydrate.DslPackage.vsix.zip
