### ISSUE TITLE
Entity Naming Conflict - Not fully resolving entity name when creating relation to associated table.

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#54]
Using version 7.0.0.229 and a new model.

I have an entity called License, it blows up `Entities.Generated.cs` with an ambiguous reference error.   I was forced to modify the line and fully resolve the Class Name. In this case the line becomes `modelBuilder.Entity<Entity.License>()` .  It is a little strange because the rest of the `modelBuilder` calls in this function appear to be fully resolved.  

In this instance I had created a reference to an `associated table`.  I will fully resolve it for now.   If I get a chance I will attempt to locate the offending generation code.

**Comment by midnight-sun** [comment]
Found the issue in the loop that starts on line 625 of [ContextGeneratedTemplate](https://github.com/nHydrate/nHydrate/blob/master/Source/nHydrate.Generator.EFCodeFirstNetCore/Generators/Contexts/ContextGeneratedTemplate.cs)

The loop for `non-associative` tables fully resolved the entity name, while this loop does not.

If I get a moment I will create a pull request.  You may get there first.

**Comment by gravbox** [comment]
Do not worry about the pull request. I have found the issue. This fix will be out soon. Thanks.
