### ISSUE TITLE
List Initialization - How To

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#55]
I am using version 7.0.0.230, and I intend to create a new entity and add it to the context.  I need an ICollection initialized so that I can add to it.

I need to do something similar to this;

    var obj = new Animal();
    obj.Name = "Kangaroo";
    obj.AnimalColors.Add(new AnimalColor { ColorID = 1 }); //1 is brown
    ctx.Add(obj);
    ctx.SaveChanges();

With the version of nHydrate I have now, the `ICollection<AnimalColors>` is null and I cannot initialize it because the `set` is `protected internal`.  Did I miss something, is there a preferred method to accomplish this feat without saving multiple times?

Steve

**Comment by midnight-sun** [comment]
nevermind, I just haven't aged well with the times.  I was missing something.
I just loaded the collection to add to it.

`ctx.Entry(saved).Collection(x => x.AnimalColorsList).Load();`

**Comment by gravbox** [comment]
You should be able to create new list. This has been changed. The navigation properties will be public get/set in the next version. Thanks.
