### ISSUE TITLE
Cannot set root to null w/ versionHistoryList

### ISSUE THREAD

**Issue by jcracknell** [nHydrate/nHydrate#56]
There appears to be a bug here where `ModelRoot._versionHistoryList` needs to be initialized in the constructor so it can inherit the root:
https://github.com/nHydrate/nHydrate/blob/b4498a4a5644301de4582281565719ee59753a99/Source/nHydrate.Generator/Models/ModelRoot.cs#L27

If you attempt to generate a model that has a `versionHistoryList` in `generating.sql.lastgen`it blows up trying to populate the list. Curiously we've had this issue with some models but not with others, which suggests that there was an intermediary version where the list was added.

For the moment we can work around this by manually replacing the list with an empty `<versionHistoryList />` element.

**Comment by gravbox** [comment]
Please try the new version 7.1.0.234 just published and let me know if it fixed this issue for you.

**Comment by jcracknell** [comment]
Yes, that appears to have fixed it thanks.
