### ISSUE TITLE
Can no longer AllowAuditTracking

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#57]
Hey Chris,

Is there a reason why this was removed in v234?  I rely pretty heavily on this functionality and am wondering if this is permanent/accidental/temporary.

Can you advise, so we can investigate options?

Thanks,

Steve

**Comment by midnight-sun** [comment]
@gravbox I'm annoyingly going to bump this, sorry.

**Comment by midnight-sun** [comment]
@gravbox again, I am anxiously awaiting to hear the roadmap for this functionality.

**Comment by gravbox** [comment]
I am sorry but this was not implemented in the .NET core version. It is still in the .NET framework version but for Core the functionality was slimmed down. At present there are no plans to add this functionality in the Core line.

**Comment by midnight-sun** [comment]
@gravbox so you know a model that had this enabled still has the audit triggers scripted and installed on a new database.  The tables are not, they are no longer scripted.  I will attempt to track this code down and submit a separate issue.

I'd love for even the sql part of this functionality to be reenabled. :(
