### ISSUE TITLE
Reorder Properties in an Entity within Visual Modeler

### ISSUE THREAD

**Issue by Trusted-Villages-Chris-Flynn** [nHydrate/nHydrate#58]
It appears the ability to reorder properties in an entity within the Visual Modeler is not supported. This is an important aspect for readability and maintenance over the course of a project. Inevitably new features will be required which will necessitate adding properties.   Not being able to easily place these new properties in a suitable order is a big deficiency.

**Comment by Trusted-Villages-Chris-Flynn** [comment]
Additional Info: This is related to using nHydrate with .NET Core 3.1 and VS 2019 v16.5.4.

**Comment by gravbox** [comment]
Yes you are correct, there is no way to re-order fields in the model. I realize that this is a preference but there are no plans to add this.

**Comment by Trusted-Villages-Chris-Flynn** [comment]
As a workaround I discovered I could just change the sortorder tags in the XML to achieve what I need. Not efficient but effective.
