### ISSUE TITLE
Bad SQL Upgrade Script - Rename Column with Index and make Not Null

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#61]
So the column previously existed with an index, I renamed it, made it not null, added a relationship. 
 This upgrade is not generated in a functional manor.  Currently it is in this order;

1. rename column
2. rename index
3. make not null
4. add the foreign_key

This fails because the index exists.  I think the index should be removed and recreated.

Steve

_Originally posted by @midnight-sun in https://github.com/nHydrate/nHydrate/issues/60#issuecomment-620979085_

**Comment by midnight-sun** [comment]
My best guess for the cause is;
/Source/nHydrate.Core.SQLGeneration/SQLEmit.cs > Line 536.
I think that this if statement needs to happen if you modify nullability as well and/or the datatype.

Steve

**Comment by gravbox** [comment]
The logic has been changed for this logic to this code.

`
if (oldColumn.DataType != newColumn.DataType || oldColumn.AllowNull != newColumn.AllowNull)
`
