### ISSUE TITLE
BreakLines extension method causes most upgrade statements to be discarded running on Linux

### ISSUE THREAD

**Issue by jcracknell** [nHydrate/nHydrate#63]
The BreakLines extension method is broken because it does not handle Unix line endings. As a result this code causes most upgrade statements to be discarded as comments:

https://github.com/nHydrate/nHydrate/blob/1e308a24ea11155e3f33a51cf9ff8f810f4ef097/Source/nHydrate.Generator.SQLInstaller/ProjectItemGenerators/DatabaseEmbeddedClasses/SqlServers.cs#L266

The implementation should probably be something like:

```cs
List<string> BreakLines(this string str) =>
  string.IsNullOrWhitespace(str) ? new List<string>(0) : new Regex("\r?\n").Split(text).ToList();
```

This most likely occurs due to the use of `StringBuilder.AppendLine` to assemble scripts which presumably uses `\n` on Linux.

**Comment by gravbox** [comment]
This is being addressed in the next release in the next few days. The universal fix will be to standardize all line endings and then split.
`

            if (string.IsNullOrEmpty(text)) return new List<string>();
            return text.Replace("\x01", string.Empty)
                .Replace("\r\n", "\n") //convert all Windows to Linux endings
                .Split('\n', StringSplitOptions.None) //split on Linux endings
                .ToList();
`
