### ISSUE TITLE
Generate model to a PostgreSQL: is it possible?

### ISSUE THREAD

**Issue by LuciferSam86** [nHydrate/nHydrate#71]
Hello,
I want to generate a model to a PostgreSQL database
When I click "generate" I don't see PostgreSQL? What am I missing?
Because from the screenshots I see an "PostgreSQL Installer" from the "Getting started" page: https://github.com/nHydrate/nHydrate/wiki/Getting-Started
![immagine](https://user-images.githubusercontent.com/8456295/96858656-d9e4d280-1460-11eb-9084-250bea930b99.png)

Thank you!

**Comment by gravbox** [comment]
Yes, please try with the newest version 7.0.1.240.
