### ISSUE TITLE
Model update from 236 to 240 drops all root-level model properties on the floor

### ISSUE THREAD

**Issue by jcracknell** [nHydrate/nHydrate#81]
Had to manually restore the project name, company, namespace, audit column names, etc despite the fact that they were still present in `{model}.nhydrate`, most likely related to the introduction of `_{model}/model.xml`.

**Comment by gravbox** [comment]
Yea sorry, these properties were not loaded correctly. The next push will save all files as Yaml, so the entire persistence layer has been rewritten.
