### ISSUE TITLE
Null Connection String on Create Database

### ISSUE THREAD

**Issue by benkansas** [nHydrate/nHydrate#92]
When attempting to use the Install project to create a new database the connection string value from the Configuration is receiving a NULL value:
![image](https://user-images.githubusercontent.com/8353348/129408989-7fce0fa7-a888-4312-8534-f890e5134046.png)

Here are the arguments from the properties screen:
![image](https://user-images.githubusercontent.com/8353348/129409382-651cb78e-24f3-4b77-b2d8-c74e6f8ceb20.png)

And the args in the main:
![image](https://user-images.githubusercontent.com/8353348/129409214-9457829d-c8dd-4a45-81fb-4865286fffa8.png)

Any reason that the Configuration wouldn't be grabbing the connection string from the command line arguments?

**Comment by benkansas** [comment]
When you look at the Data for the Configuration for the CommandLine Args the connection strings seem malformed.  "server, servername;initial catalog ..." instead of "server=servername;initial catalog ...":
![image](https://user-images.githubusercontent.com/8353348/129410439-353ff1fd-e67c-4e2e-a1b9-77e5910cdaaa.png)

**Comment by midnight-sun** [comment]
the examples here [MS](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.commandlineconfigurationextensions.addcommandline?view=dotnet-plat-ext-5.0) seem to indicate that the older formats in the nhydrate documentation are wrong.

what version of nhydrate are you using?

**Comment by benkansas** [comment]
7.1.1.250.

This was the vanilla Program.cs in the generated .Install project.

**Comment by benkansas** [comment]
@midnight-sun , based on your link, it appears the format for specifying keys in the wiki and in the comments of Program.cs has changed.  The new format should be:
`/create /newdb=TestProject /master="server=.;initial catalog=master;Integrated Security=SSPI;" /connectionstring="server=.;initial catalog=TestProject;Integrated Security=SSPI;"
`

Although, this seems to be not quite complete as the ConfigurationBuilder is identifying the `/newdb=TestProject` as value of the key `/create`.  And seems to completely skip `/master=`.

**Comment by midnight-sun** [comment]
@benkansas,

unfortunately I do not have an example using version `>240` or using `/create`, but it appears as in [250](https://github.com/nHydrate/nHydrate/blob/688edd713df26d41867f38794b49d6227c2bc44f/Source/nHydrate.Generator.SQLInstaller/ProjectItemGenerators/DatabaseEmbeddedClasses/DatabaseInstaller.cs#L30) `/create` is no longer possible.  

it was explicitly removed in a commit in [November](https://github.com/nHydrate/nHydrate/pull/76/commits/1fc9717600505e2e22d749dd71a25f7fa01f3b96).  I have been always dealing with creates/installs by;
1. manually create db / user
2. upgrade the empty db to the current version.
```csharp
var installer = new DatabaseInstaller();
installer.Install(new Install.InstallSetup {
                InstallStatus = InstallStatusConstants.Upgrade,
                Version = installer.IsVersioned(connectionString) ? null : new Install.GeneratedVersion(-1, -1, -1, -1, -1),
                ConnectionString = connectionString,
                UseTransaction = true,
                SuppressUI = true,
                AcceptVersionWarningsNewScripts = true,
                AcceptVersionWarningsChangedScripts = true
            });
```

**Comment by benkansas** [comment]
@midnight-sun ,

Any idea on why it was removed? I don't see any comments on the commit for the removal.

This was nice functionality for me, since I could hand the installer off to the infrastructure team, reducing documenting how to create a new DB and the amount of work they had to do to set it up.

Perhaps, @gravbox, you can comment?

**Comment by gravbox** [comment]
OK there are a couple of things that have changed. First the way parameters are read must be in format "param=value". There needs to be an equal sign in the middle. These are name value pairs. The "/create" syntax would not work.

Also following the Linux syntax, the parameters are following this syntax:
--update=true --connectionstring="my connection string"

The second change is that the installer no longer creates a database. I know that this was useful, as I used it as well. However moving to Core and supporting Postgres required a change. This is actually good a more correct solution as really even in SQL you should specify the initial size, disk, etc to create a database. This simply is not implemented anymore.

**Comment by benkansas** [comment]
@gravbox & @midnight-sun 

Thanks for the update on this.

Do you need anyone to update the documentation for this?  Most of the documentation still indicates that `/create` is valid.

**Comment by gravbox** [comment]
I am sorry, but there is no further development being done.
