### ISSUE TITLE
How do I use nHydrate to display an existing DBContext in my project

### ISSUE THREAD

**Issue by DBrennanMarine** [nHydrate/nHydrate#93]
Hi,
I have a data access .Net Core project that already has a DBContext class with all my entities. When I add nHydrate to this project it doesn't find my existing DBContext and the entities in it. How can I get it to use an existing DBContext and display a map of the existing entities?
Thanks,
Dave.

**Comment by gravbox** [comment]
It does not work that way. The modeler was design to be the authority. It does not read an existing context, it creates and manages the context and all its entities. The visual designer was designed to be the model and not look at other models/contexts. So you have to start with the modeler first and not have some existing project. That said, there is no further development being done now. I am sorry. It has served its purpose and is being retired.
