### ISSUE TITLE
Updating Versioned database results in error.

### ISSUE THREAD

**Issue by benkansas** [nHydrate/nHydrate#94]
When updating a versioned database (that has been created from unversioned blank database) I am getting the following error and the database is not updated to the latest version:
![image](https://user-images.githubusercontent.com/8353348/135495499-af44d93e-f0b7-490f-9889-1757f2f79560.png)

Steps to Recreate:
1.  Create Database Model.
2. Generate DAL and Installer.
3. Manually create DB/DB User on DB server (blank database).
4. Update Database model with new change.
5. Re-generate DAL and Installer
6. Run nHydrate installer to update blank database to your model.
7. Make new change to database model.
8. Re-generate DAL and Installer.
9. Run installer to update DB to current version.

Any advice on how to work-around this issue?

**Comment by benkansas** [comment]
Error appears to occur on line 344 of UpgradeInstaller.cs:
![image](https://user-images.githubusercontent.com/8353348/135497940-bf9f207e-02d5-4782-a307-c6d22b9bc4b0.png)

Does the code block 346-355 need to be moved inside the if statement replacing the exception at 344?

**Comment by midnight-sun** [comment]
I will generally run the installer accepting the warnings automatically.

But for clarity.  What is the version of your database, and what is the latest version of your DAL?

**Comment by gravbox** [comment]
I am not sure if the code should be moved to replace the exception. The idea was to fail the upgrade if there was a script with a lower version that had changed, if warnings were not suppressed. The idea is if a developer changed a previous script lower than the database version, it will never get run. This might be a problem and there should be some way of noticing the runner. Knowing that and that there is no real error, please feel free to modify or remove this exception if desired. I am sorry, but there is no further development being done.
