### ISSUE TITLE
nHydrate and VS2022

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#95]
Hey @gravbox,

Is there a plan to update the extension to be vs2022 compatible?

Please advise,

-Steve

**Comment by midnight-sun** [comment]
it seems the issue might be related to x64 (as thats the version of vs2022 I installed)
[link to vs docs](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#extensions-written-in-a-net-language)

**Comment by gravbox** [comment]
I am sorry, but there is no further development going on.
