### ISSUE TITLE
Remove file copy post-build events in project templates

### ISSUE THREAD

**Issue by jcracknell** [nHydrate/nHydrate#96]
All of the nHydrate project templates contain a post-build event which attempts to copy the compiled output to to the solution folder eg:

https://github.com/nHydrate/nHydrate/blob/c20d49492d9392c4ef1f40bf755ba0b65fa1a89d/Source/nHydrate.Core.SQLGeneration/nHydrate.Core.SQLGeneration.csproj#L86-L88

As best I can tell this does nothing useful, breaks the build on Linux, and pollutes the repository with binaries outside of conventionally excluded paths.

**Comment by gravbox** [comment]
This was left over from some years ago. However you can just remove this statement and it will not be over generated. I am sorry, but there is no further development being done. So just remove these statements and they should not be a problem.
